// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Batleforc",
            "url": "https://weebo.fr",
            "email": "maxleriche.60@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/route.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login return",
                        "schema": {
                            "$ref": "#/definitions/route.LoginReturn"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "Logout user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "parameters": [
                    {
                        "description": "Logout body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/route.LogoutBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/renewtoken": {
            "post": {
                "description": "Renew Token via refresh token",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Renew Token",
                "parameters": [
                    {
                        "description": "Renew body",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/route.RenewTokenBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Renew return",
                        "schema": {
                            "$ref": "#/definitions/route.RenewTokenReturn"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "route.LoginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "route.LoginReturn": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "pseudo": {
                    "type": "string"
                },
                "renew_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "route.LogoutBody": {
            "type": "object",
            "properties": {
                "renew_token": {
                    "type": "string"
                }
            }
        },
        "route.RenewTokenBody": {
            "type": "object",
            "properties": {
                "renew_token": {
                    "type": "string"
                }
            }
        },
        "route.RenewTokenReturn": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "pseudo": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Bipper Api",
	Description:      "Bipper api",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
